/*
 * AUTOGENERATED - DON'T EDIT
 * Your edits in this file will be overwritten in the next build!
 * Modify the docusaurus.config.js file at your site's root instead.
 */
export default {
  "title": "潜心专研前端的Peyton",
  "titleDelimiter": "-",
  "url": "https://zhangqiang.vercel.app",
  "baseUrl": "/",
  "favicon": "https://dscache.tencent-cloud.cn/upload/uploader/999-12e331ae5bd4149e615b9056a1a05b198a70c0d7.png",
  "organizationName": "zhangqiang",
  "projectName": "zhangqiang.vercel.app",
  "themeConfig": {
    "navbar": {
      "title": "潜心专研前端的Peyton",
      "logo": {
        "alt": "潜心专研前端的Peyton",
        "src": "https://dscache.tencent-cloud.cn/upload/uploader/999-12e331ae5bd4149e615b9056a1a05b198a70c0d7.png",
        "srcDark": "https://dscache.tencent-cloud.cn/upload/uploader/999-12e331ae5bd4149e615b9056a1a05b198a70c0d7.png"
      },
      "items": [
        {
          "type": "localeDropdown",
          "position": "left",
          "dropdownItemsBefore": [],
          "dropdownItemsAfter": []
        },
        {
          "to": "docs/all-intro",
          "label": "专属学习笔记",
          "position": "right"
        },
        {
          "label": "小工具",
          "position": "right",
          "items": [
            {
              "label": "同比增减在线换算工具",
              "to": "https://tools.zhangqiang.hk.cn/"
            },
            {
              "label": "简易的rap参数转ts格式工具",
              "to": "https://jack-zhang-coming.github.io/rap-to-ts/"
            }
          ]
        }
      ],
      "hideOnScroll": false
    },
    "algolia": {
      "apiKey": "fabfb0e9997e101154ed85d64b7b6a3c",
      "indexName": "ZXUQIANCN",
      "appId": "LIJMO3C9C4",
      "contextualSearch": true,
      "searchParameters": {},
      "searchPagePath": "search"
    },
    "footer": {
      "style": "dark",
      "copyright": "<p>Copyright © 2023 潜心专研前端的Peyton (樊鹏) Built with Peytonfan.</p><p><a style=\"color: hsl(210deg, 100%, 80%)\" href='http://beian.miit.gov.cn'>陕ICP备2023010513号-1</a></p><a rel=\"license\" href=\"https://github.com/JACK-ZHANG-coming/my-now-blog\">转载于github 潜心专研的小张同学</a><br />",
      "links": []
    },
    "prism": {
      "theme": {
        "plain": {
          "color": "#393A34",
          "backgroundColor": "#f6f8fa"
        },
        "styles": [
          {
            "types": [
              "comment",
              "prolog",
              "doctype",
              "cdata"
            ],
            "style": {
              "color": "#999988",
              "fontStyle": "italic"
            }
          },
          {
            "types": [
              "namespace"
            ],
            "style": {
              "opacity": 0.7
            }
          },
          {
            "types": [
              "string",
              "attr-value"
            ],
            "style": {
              "color": "#e3116c"
            }
          },
          {
            "types": [
              "punctuation",
              "operator"
            ],
            "style": {
              "color": "#393A34"
            }
          },
          {
            "types": [
              "entity",
              "url",
              "symbol",
              "number",
              "boolean",
              "variable",
              "constant",
              "property",
              "regex",
              "inserted"
            ],
            "style": {
              "color": "#36acaa"
            }
          },
          {
            "types": [
              "atrule",
              "keyword",
              "attr-name",
              "selector"
            ],
            "style": {
              "color": "#00a4db"
            }
          },
          {
            "types": [
              "function",
              "deleted",
              "tag"
            ],
            "style": {
              "color": "#d73a49"
            }
          },
          {
            "types": [
              "function-variable"
            ],
            "style": {
              "color": "#6f42c1"
            }
          },
          {
            "types": [
              "tag",
              "selector",
              "keyword"
            ],
            "style": {
              "color": "#00009f"
            }
          }
        ]
      },
      "darkTheme": {
        "plain": {
          "backgroundColor": "#282c34",
          "color": "#ffffff"
        },
        "styles": [
          {
            "types": [
              "attr-name"
            ],
            "style": {
              "color": "#c5a5c5"
            }
          },
          {
            "types": [
              "attr-value"
            ],
            "style": {
              "color": "#8dc891"
            }
          },
          {
            "types": [
              "comment",
              "block-comment",
              "prolog",
              "doctype",
              "cdata",
              "shebang"
            ],
            "style": {
              "color": "#999999"
            }
          },
          {
            "types": [
              "property",
              "number",
              "function-name",
              "constant",
              "symbol",
              "deleted"
            ],
            "style": {
              "color": "#5a9bcf"
            }
          },
          {
            "types": [
              "boolean"
            ],
            "style": {
              "color": "#ff8b50"
            }
          },
          {
            "types": [
              "tag"
            ],
            "style": {
              "color": "#fc929e"
            }
          },
          {
            "types": [
              "string"
            ],
            "style": {
              "color": "#8dc891"
            }
          },
          {
            "types": [
              "punctuation"
            ],
            "style": {
              "color": "#8dc891"
            }
          },
          {
            "types": [
              "selector",
              "char",
              "builtin",
              "inserted"
            ],
            "style": {
              "color": "#D8DEE9"
            }
          },
          {
            "types": [
              "function"
            ],
            "style": {
              "color": "#79b6f2"
            }
          },
          {
            "types": [
              "operator",
              "entity",
              "url",
              "variable"
            ],
            "style": {
              "color": "#d7deea"
            }
          },
          {
            "types": [
              "keyword"
            ],
            "style": {
              "color": "#c5a5c5"
            }
          },
          {
            "types": [
              "at-rule",
              "class-name"
            ],
            "style": {
              "color": "#FAC863"
            }
          },
          {
            "types": [
              "important"
            ],
            "style": {
              "fontWeight": "400"
            }
          },
          {
            "types": [
              "bold"
            ],
            "style": {
              "fontWeight": "bold"
            }
          },
          {
            "types": [
              "italic"
            ],
            "style": {
              "fontStyle": "italic"
            }
          },
          {
            "types": [
              "namespace"
            ],
            "style": {
              "opacity": 0.7
            }
          }
        ]
      },
      "defaultLanguage": "javascript",
      "additionalLanguages": [],
      "magicComments": [
        {
          "className": "theme-code-block-highlighted-line",
          "line": "highlight-next-line",
          "block": {
            "start": "highlight-start",
            "end": "highlight-end"
          }
        }
      ]
    },
    "colorMode": {
      "defaultMode": "light",
      "disableSwitch": false,
      "respectPrefersColorScheme": false
    },
    "docs": {
      "versionPersistence": "localStorage",
      "sidebar": {
        "hideable": false,
        "autoCollapseCategories": false
      }
    },
    "metadata": [],
    "tableOfContents": {
      "minHeadingLevel": 2,
      "maxHeadingLevel": 3
    }
  },
  "presets": [
    [
      "@docusaurus/preset-classic",
      {
        "docs": {
          "sidebarPath": "/Users/fanpeng/Downloads/myblog-main/sidebars.js",
          "remarkPlugins": [
            null
          ],
          "rehypePlugins": [
            null
          ],
          "showLastUpdateTime": true
        },
        "blog": {
          "path": "./blog",
          "routeBasePath": "/",
          "blogSidebarTitle": "近期文章",
          "remarkPlugins": [
            null
          ],
          "rehypePlugins": [
            null
          ],
          "feedOptions": {
            "type": "all",
            "title": "峰华前端工程师1111",
            "copyright": "Copyright © 2023 2222峰华 (张旭乾) Built with Docusaurus.<p><a href=\"http://beian.miit.gov.cn/\">冀ICP备14007097号-3</a></p>"
          }
        },
        "theme": {
          "customCss": "/Users/fanpeng/Downloads/myblog-main/src/css/custom.css"
        },
        "sitemap": {
          "changefreq": "daily",
          "priority": 0.5
        }
      }
    ]
  ],
  "plugins": [
    "/Users/fanpeng/Downloads/myblog-main/src/plugin/plugin-baidu-analytics",
    "/Users/fanpeng/Downloads/myblog-main/src/plugin/plugin-baidu-push",
    "/Users/fanpeng/Downloads/myblog-main/src/plugin/plugin-google-adsense",
    "/Users/fanpeng/Downloads/myblog-main/src/plugin/plugin-onesignal-push",
    "docusaurus2-dotenv",
    [
      "@docusaurus/plugin-content-blog",
      {
        "id": "lifestyle-blog",
        "routeBasePath": "lifestyle",
        "path": "./lifestyle",
        "feedOptions": {
          "type": "all",
          "title": "峰华前端工程师2222",
          "copyright": "Copyright © 2023 3333峰华 (张旭乾) Built with Docusaurus.<p><a href=\"http://beian.miit.gov.cn/\">冀ICP备14007097号-3</a></p>"
        }
      }
    ]
  ],
  "stylesheets": [
    {
      "rel": "preconnect",
      "href": "https://fonts.gstatic.com",
      "type": "text/css"
    },
    {
      "href": "/katex/katex.min.css",
      "type": "text/css",
      "integrity": "sha384-AfEj0r4/OFrOo5t7NnNe46zW/tFgW6x/bCJG8FqQCEo3+Aro6EYUG4+cU+KJWu/X",
      "crossorigin": "anonymous"
    },
    {
      "href": "https://fonts.font.im/css?family=Raleway:500,700&display=swap",
      "type": "text/css",
      "rel": "stylesheet"
    }
  ],
  "i18n": {
    "defaultLocale": "zh-CN",
    "locales": [
      "zh-CN"
    ],
    "localeConfigs": {
      "zh-CN": {
        "label": "中文",
        "direction": "ltr"
      },
      "en": {
        "label": "English",
        "direction": "ltr"
      }
    }
  },
  "baseUrlIssueBanner": true,
  "onBrokenLinks": "throw",
  "onBrokenMarkdownLinks": "warn",
  "onDuplicateRoutes": "warn",
  "staticDirectories": [
    "static"
  ],
  "customFields": {},
  "themes": [],
  "scripts": [],
  "clientModules": [],
  "tagline": "",
  "noIndex": false
};
